version: '3.8'

services:
  qwen-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: qwen-server:latest
    container_name: qwen-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8002:8002"
    volumes:
      - ./models:/app/models  # 挂载本地模型目录
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - qwen-network

networks:
  qwen-network:
    driver: bridge
